
name: Ubuntu CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Building for coverage
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="--coverage"
        cmake --build build

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Check Python version
      run: python --version

    - name: Install dependencies for tests
      run: |
        python -m pip install --upgrade pip
        pip install --force-reinstall -r tests/requirements.txt

    - name: Running tests
      run: ${{ github.workspace }}/test.sh

    - name: Install lcov for coverage
      run: sudo apt-get install lcov -y

    - name: Generating coverage report
      run: |
        lcov --capture --directory build --output-file lcov.info

    - name: Uploading coverage report
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      run: |
        bash <(curl -Ls https://coverage.codacy.com/get.sh)
